name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make a commit to maintain streak
        run: |
          date >> README.md
          git config --global user.name "Your Name"
          git config --global user.email "nirajan.acharya666@gmail.com"
          git add README.md
          git commit -m "Auto commit to maintain streak"
          git push https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
