name: Auto Commit and Maintain Streak

on:
  schedule:
    - cron: '5 3 * * *' # Runs daily at 8:50 AM Nepal Time (UTC+5:45)

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make changes or update a file to ensure there's a commit
      - name: Make a commit
        run: |
          # Append the current date to a file or make a change
          echo "Auto-commit on $(date)" >> autocommit.txt
          # Configure Git
          git config --global user.email "nirajanacharya666@gmail.com"
          git config --global user.name "Nirajan Acharya"
          # Stage and commit changes
          git add autocommit.txt
          git commit -m "Auto-commit to maintain contribution streak" || echo "No changes to commit"

      # Step 3: Push the changes
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git push https://nirajanacharya666:${{ secrets.GH_PAT }}@github.com/nirajanacharya/repo-name.git
